name: CI
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.repository }}
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  #  swagger_lint:
  #    runs-on: ubuntu-latest
  #    name: Swagger Editor Validator Remote
  #
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Validate OpenAPI definition
  #        uses: char0n/apidom-validate@v1
  #        with:
  #          fails-on: 2
  #          definition-file: spec/oas_v1.yaml

  lint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint with Prettier
        run: yarn check-prettier
